spring:
  application:
    name: brokage-application
  datasource:
    url: jdbc:h2:mem:brokage
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  security:
    jwt:
      secret-key: DEFINESOMESECRETKEYTOSINGTOKENFORSECURINGAPPLICATIONWITHJWTTOKEN
      expiration: 86400000 # 1 day

server:
  port: 8222
#
#logging:
#  level:
#    org.springframework: DEBUG